///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace MyTest1
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the MyTest1Repository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("3dfa61cb-f1c2-449d-83e1-284b1fbd9842")]
    public partial class MyTest1Repository : RepoGenBaseFolder
    {
        static MyTest1Repository instance = new MyTest1Repository();
        MyTest1RepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;

        /// <summary>
        /// Gets the singleton class instance representing the MyTest1Repository element repository.
        /// </summary>
        [RepositoryFolder("3dfa61cb-f1c2-449d-83e1-284b1fbd9842")]
        public static MyTest1Repository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public MyTest1Repository() 
            : base("MyTest1Repository", "/", null, 0, false, "3dfa61cb-f1c2-449d-83e1-284b1fbd9842", ".\\RepositoryImages\\MyTest1Repository3dfa61cb.rximgres")
        {
            _applicationundertest = new MyTest1RepositoryFolders.ApplicationUnderTestAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("3dfa61cb-f1c2-449d-83e1-284b1fbd9842")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("8aefcf23-5d42-4100-abda-e414f868c905")]
        public virtual MyTest1RepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class MyTest1RepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("8aefcf23-5d42-4100-abda-e414f868c905")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _featuresInfo;
            RepoItemInfo _solutionsInfo;
            RepoItemInfo _pricingInfo;
            RepoItemInfo _resourcesInfo;

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/dom[@domain='www.ranorex.com']", parentFolder, 30000, null, false, "8aefcf23-5d42-4100-abda-e414f868c905", "")
            {
                _featuresInfo = new RepoItemInfo(this, "FEATURES", ".//li[#'productMenuButton']/span[@innertext='FEATURES']", "", 30000, null, "5014d696-8ec4-4891-917b-785fff4a16d8");
                _solutionsInfo = new RepoItemInfo(this, "SOLUTIONS", ".//li[#'solutionMenuButton']/span[@innertext='SOLUTIONS']", "", 30000, null, "b75b56c1-9855-4325-a177-9759f83253f1");
                _pricingInfo = new RepoItemInfo(this, "PRICING", ".//div[#'rx-header-sticky-content-wrapper']//ul/li[3]/a[@innertext='PRICING']", "", 30000, null, "88ec3cd3-e84d-49fd-ae08-381f8be8bb75");
                _resourcesInfo = new RepoItemInfo(this, "RESOURCES", ".//div[#'rx-header-sticky-content-wrapper']//ul/li[4]/a[@innertext='RESOURCES']", "", 30000, null, "404e07e8-10b9-4692-ba9b-38175b6c4b37");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("8aefcf23-5d42-4100-abda-e414f868c905")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("8aefcf23-5d42-4100-abda-e414f868c905")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The FEATURES item.
            /// </summary>
            [RepositoryItem("5014d696-8ec4-4891-917b-785fff4a16d8")]
            public virtual Ranorex.SpanTag FEATURES
            {
                get
                {
                    return _featuresInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The FEATURES item info.
            /// </summary>
            [RepositoryItemInfo("5014d696-8ec4-4891-917b-785fff4a16d8")]
            public virtual RepoItemInfo FEATURESInfo
            {
                get
                {
                    return _featuresInfo;
                }
            }

            /// <summary>
            /// The SOLUTIONS item.
            /// </summary>
            [RepositoryItem("b75b56c1-9855-4325-a177-9759f83253f1")]
            public virtual Ranorex.SpanTag SOLUTIONS
            {
                get
                {
                    return _solutionsInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The SOLUTIONS item info.
            /// </summary>
            [RepositoryItemInfo("b75b56c1-9855-4325-a177-9759f83253f1")]
            public virtual RepoItemInfo SOLUTIONSInfo
            {
                get
                {
                    return _solutionsInfo;
                }
            }

            /// <summary>
            /// The PRICING item.
            /// </summary>
            [RepositoryItem("88ec3cd3-e84d-49fd-ae08-381f8be8bb75")]
            public virtual Ranorex.ATag PRICING
            {
                get
                {
                    return _pricingInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The PRICING item info.
            /// </summary>
            [RepositoryItemInfo("88ec3cd3-e84d-49fd-ae08-381f8be8bb75")]
            public virtual RepoItemInfo PRICINGInfo
            {
                get
                {
                    return _pricingInfo;
                }
            }

            /// <summary>
            /// The RESOURCES item.
            /// </summary>
            [RepositoryItem("404e07e8-10b9-4692-ba9b-38175b6c4b37")]
            public virtual Ranorex.ATag RESOURCES
            {
                get
                {
                    return _resourcesInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The RESOURCES item info.
            /// </summary>
            [RepositoryItemInfo("404e07e8-10b9-4692-ba9b-38175b6c4b37")]
            public virtual RepoItemInfo RESOURCESInfo
            {
                get
                {
                    return _resourcesInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
